name: Python Test Workflow

on: [push]

jobs:
  test-python:
    runs-on: ubuntu-latest

    steps:
    - name: Kodni yuklab olish
      uses: actions/checkout@v3

    - name: Python o‘rnatish
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Test faylni ishga tushurish
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pytest
